import OAK_LOG_IMAGE from './logs_oak.png';
import WILLOW_LOG_IMAGE from './logs_willow.png';
import TEAK_LOG_IMAGE from './logs_teak.png';
import MAGIC_LOG_IMAGE from './logs_magic.png';
import MAPLE_LOG_IMAGE from './logs_maple.png';
import MAHOGANY_LOG_IMAGE from './logs_mahogany.png';
import YEW_LOG_IMAGE from './logs_yew.png';
import STICK_LOG_IMAGE from './logs_stick.png';

import SHRIMP_NORMAL_IMAGE from './shrimp_normal.png';
import SHRIMP_PRIME_IMAGE from './shrimp_prime.png';
import SHRIMP_MULTI_IMAGE from './shrimp_multi.png';
import SHRIMP_GRAND_IMAGE from './shrimp_prawn.png';

import TROUT_SALMON_IMAGE from './fish/salmon.png';
import TROUT_HERRING_IMAGE from './fish/herring.png';
import TROUT_TROUT_IMAGE from './fish/leaping_trout.png';
import TROUT_PRIME_IMAGE from './fish/trout.png';

import COPPER_ORE_IMAGE from './ores/COPPER.png';
import TIN_ORE_IMAGE from './ores/TIN.png';
import IRON_ORE_IMAGE from './ores/IRON.png';
import COAL_ORE_IMAGE from './ores/COAL.png';
import MITHRIL_ORE_IMAGE from './ores/MITHRIL.png';
import ADAMANTITE_ORE_IMAGE from './ores/ADAMANT.png';
import LUMINITE_ORE_IMAGE from './ores/LUMINITE.png';
import RUNITE_ORE_IMAGE from './ores/RUNITE.png';
import ORICHALCITE_ORE_IMAGE from './ores/ORICHALCITE.png';
import DRAKOLITH_ORE_IMAGE from './ores/DRAKOLITH.png';
import NECRITE_ORE_IMAGE from './ores/NECRITE.png';
import PHASMATITE_ORE_IMAGE from './ores/PHASMATITE.png';
import BANITE_ORE_IMAGE from './ores/BANITE.png';
import LIGHT_ANIMICA_IMAGE from './ores/LIGHT_ANIMICA.png';
import DARK_ANIMICA_IMAGE from './ores/DARK_ANIMICA.png';
import SILVER_ORE_IMAGE from './ores/SILVER.png';
import GOLD_ORE_IMAGE from './ores/GOLD.png';

import WEATHER_CLOUD_IMAGE from './weather/weather_cloud.png';
import WEATHER_RAIN_IMAGE from './weather/weather_rain.png';
import WEATHER_STORM_IMAGE from './weather/weather_storm.png';
import WEATHER_SUN_IMAGE from './weather/weather_sun.png';

import ARBUCK_SEED_IMAGE from './seeds/ARBUCK_SEED.png';
import AVACADO_SEED_IMAGE from './seeds/AVACADO_SEED.png';
import AVANTOE_SEED_IMAGE from './seeds/AVANTOE_SEED.png';
import BAR_BERRY_SEED_IMAGE from './seeds/BAR_BERRY_SEED.png';
import BLOODWEED_SEED_IMAGE from './seeds/BLOODWEED_SEED.png';
import CABBAGE_SEED_IMAGE from './seeds/CABBAGE_SEED.png';
import CADANTINE_SEED_IMAGE from './seeds/CADANTINE_SEED.png';
import CADAVA_BERRY_SEED_IMAGE from './seeds/CADAVA_BERRY_SEED.png';
import CORN_SEED_IMAGE from './seeds/CORN_SEED.png';
import DWARF_WEED_SEED_IMAGE from './seeds/DWARF_WEED_SEED.png';
import DWELL_BERRY_SEED_IMAGE from './seeds/DWELL_BERRY_SEED.png';
import FELLSTALK_SEED_IMAGE from './seeds/FELLSTALK_SEED.png';
import GUAM_SEED_IMAGE from './seeds/GUAM_SEED.png';
import HARRALANDER_SEED_IMAGE from './seeds/HARRALANDER_SEED.png';
import IRIT_SEED_IMAGE from './seeds/IRIT_SEED.png';
import JANGER_BERRY_SEED_IMAGE from './seeds/JANGER_BERRY_SEED.png';
import KWUARM_SEED_IMAGE from './seeds/KWUARM_SEED.png';
import LANTADYME_SEED_IMAGE from './seeds/LANTADYME_SEED.png';
import LYCHEE_SEED_IMAGE from './seeds/LYCHEE_SEED.png';
import MANGO_SEED_IMAGE from './seeds/MANGO_SEED.png';
import MARRENTILL_SEED_IMAGE from './seeds/MARRENTILL_SEED.png';
import ONION_SEED_IMAGE from './seeds/ONION_SEED.png';
import POTATO_SEED_IMAGE from './seeds/POTATO_SEED.png';
import RANARR_SEED_IMAGE from './seeds/RANARR_SEED.png';
import RED_BERRY_SEED_IMAGE from './seeds/RED_BERRY_SEED.png';
import SNAPDRAGON_SEED_IMAGE from './seeds/SNAPDRAGON_SEED.png';
import STRAWBERRY_SEED_IMAGE from './seeds/STRAWBERRY_SEED.png';
import TARROMIN_SEED_IMAGE from './seeds/TARROMIN_SEED.png';
import TOADFLAX_SEED_IMAGE from './seeds/TOADFLAX_SEED.png';
import TOMATO_SEED_IMAGE from './seeds/TOMATO_SEED.png';
import TORSTOL_SEED_IMAGE from './seeds/TORSTOL_SEED.png';
import WATERMELON_SEED_IMAGE from './seeds/WATERMELON_SEED.png';
import WERGALI_SEED_IMAGE from './seeds/WERGALI_SEED.png';
import WHITE_BERRY_SEED_IMAGE from './seeds/WHITE_BERRY_SEED.png';

export const OAK_LOG_ICON = OAK_LOG_IMAGE;
export const WILLOW_LOG_ICON = WILLOW_LOG_IMAGE;
export const TEAK_LOG_ICON = TEAK_LOG_IMAGE;
export const MAGIC_LOG_ICON = MAGIC_LOG_IMAGE;
export const MAPLE_LOG_ICON = MAPLE_LOG_IMAGE;
export const MAHOGANY_LOG_ICON = MAHOGANY_LOG_IMAGE;
export const YEW_LOG_ICON = YEW_LOG_IMAGE;
export const STICK_LOG_ICON = STICK_LOG_IMAGE;

export const SHRIMP_NORMAL_ICON = SHRIMP_NORMAL_IMAGE;
export const SHRIMP_PRIME_ICON = SHRIMP_PRIME_IMAGE;
export const SHRIMP_MULTI_ICON = SHRIMP_MULTI_IMAGE;
export const SHRIMP_GRAND_ICON = SHRIMP_GRAND_IMAGE;

export const TROUT_SALMON_ICON = TROUT_SALMON_IMAGE;
export const TROUT_HERRING_ICON = TROUT_HERRING_IMAGE;
export const TROUT_TROUT_ICON = TROUT_TROUT_IMAGE;
export const TROUT_PRIME_ICON = TROUT_PRIME_IMAGE;

export const COPPER_ORE_ICON = COPPER_ORE_IMAGE;
export const TIN_ORE_ICON = TIN_ORE_IMAGE;
export const IRON_ORE_ICON = IRON_ORE_IMAGE;
export const COAL_ORE_ICON = COAL_ORE_IMAGE;
export const MITHRIL_ORE_ICON = MITHRIL_ORE_IMAGE;
export const ADAMANTITE_ORE_ICON = ADAMANTITE_ORE_IMAGE;
export const GOLD_ORE_ICON = GOLD_ORE_IMAGE;
export const SILVER_ORE_ICON = SILVER_ORE_IMAGE;
export const LUMINITE_ORE_ICON = LUMINITE_ORE_IMAGE;
export const RUNITE_ORE_ICON = RUNITE_ORE_IMAGE;
export const ORICHALCITE_ORE_ICON = ORICHALCITE_ORE_IMAGE;
export const DRAKOLITH_ORE_ICON = DRAKOLITH_ORE_IMAGE;
export const NECRITE_ORE_ICON = NECRITE_ORE_IMAGE;
export const PHASMATITE_ORE_ICON = PHASMATITE_ORE_IMAGE;
export const BANITE_ORE_ICON = BANITE_ORE_IMAGE;
export const LIGHT_ANIMICA_ICON = LIGHT_ANIMICA_IMAGE;
export const DARK_ANIMICA_ICON = DARK_ANIMICA_IMAGE;

export const WEATHER_CLOUD_ICON = WEATHER_CLOUD_IMAGE;
export const WEATHER_RAIN_ICON = WEATHER_RAIN_IMAGE;
export const WEATHER_STORM_ICON = WEATHER_STORM_IMAGE;
export const WEATHER_SUN_ICON = WEATHER_SUN_IMAGE;

export const ARBUCK_SEED_ICON = ARBUCK_SEED_IMAGE;
export const AVACADO_SEED_ICON = AVACADO_SEED_IMAGE;
export const AVANTOE_SEED_ICON = AVANTOE_SEED_IMAGE;
export const BAR_BERRY_SEED_ICON = BAR_BERRY_SEED_IMAGE;
export const BLOODWEED_SEED_ICON = BLOODWEED_SEED_IMAGE;
export const CABBAGE_SEED_ICON = CABBAGE_SEED_IMAGE;
export const CADANTINE_SEED_ICON = CADANTINE_SEED_IMAGE;
export const CADAVA_BERRY_SEED_ICON = CADAVA_BERRY_SEED_IMAGE;
export const CORN_SEED_ICON = CORN_SEED_IMAGE;
export const DWARF_WEED_SEED_ICON = DWARF_WEED_SEED_IMAGE;
export const DWELL_BERRY_SEED_ICON = DWELL_BERRY_SEED_IMAGE;
export const FELLSTALK_SEED_ICON = FELLSTALK_SEED_IMAGE;
export const GUAM_SEED_ICON = GUAM_SEED_IMAGE;
export const HARRALANDER_SEED_ICON = HARRALANDER_SEED_IMAGE;
export const IRIT_SEED_ICON = IRIT_SEED_IMAGE;
export const JANGER_BERRY_SEED_ICON = JANGER_BERRY_SEED_IMAGE;
export const KWUARM_SEED_ICON = KWUARM_SEED_IMAGE;
export const LANTADYME_SEED_ICON = LANTADYME_SEED_IMAGE;
export const LYCHEE_SEED_ICON = LYCHEE_SEED_IMAGE;
export const MANGO_SEED_ICON = MANGO_SEED_IMAGE;
export const MARRENTILL_SEED_ICON = MARRENTILL_SEED_IMAGE;
export const ONION_SEED_ICON = ONION_SEED_IMAGE;
export const POTATO_SEED_ICON = POTATO_SEED_IMAGE;
export const RANARR_SEED_ICON = RANARR_SEED_IMAGE;
export const RED_BERRY_SEED_ICON = RED_BERRY_SEED_IMAGE;
export const SNAPDRAGON_SEED_ICON = SNAPDRAGON_SEED_IMAGE;
export const STRAWBERRY_SEED_ICON = STRAWBERRY_SEED_IMAGE;
export const TARROMIN_SEED_ICON = TARROMIN_SEED_IMAGE;
export const TOADFLAX_SEED_ICON = TOADFLAX_SEED_IMAGE;
export const TOMATO_SEED_ICON = TOMATO_SEED_IMAGE;
export const TORSTOL_SEED_ICON = TORSTOL_SEED_IMAGE;
export const WATERMELON_SEED_ICON = WATERMELON_SEED_IMAGE;
export const WERGALI_SEED_ICON = WERGALI_SEED_IMAGE;
export const WHITE_BERRY_SEED_ICON = WHITE_BERRY_SEED_IMAGE;
