import {
    OAK_LOG_ICON,
    WILLOW_LOG_ICON,
    TEAK_LOG_ICON,
    MAGIC_LOG_ICON,
    MAPLE_LOG_ICON,
    MAHOGANY_LOG_ICON,
    YEW_LOG_ICON,
    STICK_LOG_ICON,
    SHRIMP_NORMAL_ICON, SHRIMP_MULTI_ICON, SHRIMP_GRAND_ICON, SHRIMP_PRIME_ICON, TROUT_HERRING_ICON, TROUT_SALMON_ICON, TROUT_PRIME_ICON, TROUT_TROUT_ICON, ADAMANTITE_ORE_ICON, BANITE_ORE_ICON, COAL_ORE_ICON, COPPER_ORE_ICON, DARK_ANIMICA_ICON, DRAKOLITH_ORE_ICON, IRON_ORE_ICON, LIGHT_ANIMICA_ICON, LUMINITE_ORE_ICON, MITHRIL_ORE_ICON, NECRITE_ORE_ICON, ORICHALCITE_ORE_ICON, PHASMATITE_ORE_ICON, RUNITE_ORE_ICON, TIN_ORE_ICON
} from '../images/itemImages'
import { InventoryItem } from '../models/Item'

export const OAK_LOG = 'OAK_LOG'
export const WILLOW_LOG = 'WILLOW_LOG'
export const TEAK_LOG = 'TEAK_LOG'
export const MAGIC_LOG = 'MAGIC_LOG'
export const MAPLE_LOG = 'MAPLE_LOG'
export const MAHOGANY_LOG = 'MAHOGANY_LOG'
export const YEW_LOG = 'YEW_LOG'
export const STICK = 'STICK'


export const COPPER_ORE = 'COPPER_ORE'
export const TIN_ORE = 'TIN_ORE'
export const IRON_ORE = 'IRON_ORE'
export const COAL_ORE = 'COAL_ORE'
export const MITHRIL_ORE = 'MITHRIL_ORE'
export const ADAMANTITE_ORE = 'ADAMANTITE_ORE'
export const LUMINITE_ORE = 'LUMINITE_ORE'
export const RUNITE_ORE = 'RUNITE_ORE'
export const ORICHALCITE_ORE = 'ORICHALCITE_ORE'
export const DRAKOLITH_ORE = 'DRAKOLITH_ORE'
export const NECRITE_ORE = 'NECRITE_ORE'
export const PHASMATITE_ORE = 'PHASMATITE_ORE'
export const BANITE_ORE = 'BANITE_ORE'
export const LIGHT_ANIMICA = 'LIGHT_ANIMICA'
export const DARK_ANIMICA = 'DARK_ANIMICA'


export const SHRIMP_NORMAL = 'SHRIMP_NORMAL'
export const SHRIMP_PRIME = 'SHRIMP_PRIME'
export const SHRIMP_PRAWN = 'SHRIMP_PRAWN'
export const SHRIMP_MULTI = 'SHRIMP_MULTI'

export const TROUT_HERRING = 'TROUT_HERRING'
export const TROUT_PRIME = 'TROUT_PRIME'
export const TROUT_SALMON = 'TROUT_SALMON'
export const TROUT_TROUT = 'TROUT_TROUT'

export const itemImages = {
    [OAK_LOG]: OAK_LOG_ICON,
    [WILLOW_LOG]: WILLOW_LOG_ICON,
    [TEAK_LOG]: TEAK_LOG_ICON,
    [MAGIC_LOG]: MAGIC_LOG_ICON,
    [MAPLE_LOG]: MAPLE_LOG_ICON,
    [MAHOGANY_LOG]: MAHOGANY_LOG_ICON,
    [YEW_LOG]: YEW_LOG_ICON,
    [STICK]: STICK_LOG_ICON,

    [SHRIMP_NORMAL]: SHRIMP_NORMAL_ICON,
    [SHRIMP_PRIME]: SHRIMP_PRIME_ICON,
    [SHRIMP_MULTI]: SHRIMP_MULTI_ICON,
    [SHRIMP_PRAWN]: SHRIMP_GRAND_ICON,


    [TROUT_HERRING]: TROUT_HERRING_ICON,
    [TROUT_PRIME]: TROUT_PRIME_ICON,
    [TROUT_SALMON]: TROUT_SALMON_ICON,
    [TROUT_TROUT]: TROUT_TROUT_ICON,


    [COPPER_ORE]: COPPER_ORE_ICON,
    [TIN_ORE]: TIN_ORE_ICON,
    [IRON_ORE]: IRON_ORE_ICON,
    [COAL_ORE]: COAL_ORE_ICON,
    [MITHRIL_ORE]: MITHRIL_ORE_ICON,
    [ADAMANTITE_ORE]: ADAMANTITE_ORE_ICON,
    [LUMINITE_ORE]: LUMINITE_ORE_ICON,
    [RUNITE_ORE]: RUNITE_ORE_ICON,
    [ORICHALCITE_ORE]: ORICHALCITE_ORE_ICON,
    [DRAKOLITH_ORE]: DRAKOLITH_ORE_ICON,
    [NECRITE_ORE]: NECRITE_ORE_ICON,
    [PHASMATITE_ORE]: PHASMATITE_ORE_ICON,
    [BANITE_ORE]: BANITE_ORE_ICON,
    [LIGHT_ANIMICA]: LIGHT_ANIMICA_ICON,
    [DARK_ANIMICA]: DARK_ANIMICA_ICON,
}

export const ALL_ITEMS = {
    [STICK]: new InventoryItem(STICK, 0),
    [OAK_LOG]: new InventoryItem(OAK_LOG, 0),
    [WILLOW_LOG]: new InventoryItem(WILLOW_LOG, 0),
    [TEAK_LOG]: new InventoryItem(TEAK_LOG, 0),
    [MAGIC_LOG]: new InventoryItem(MAGIC_LOG, 0),
    [MAPLE_LOG]: new InventoryItem(MAPLE_LOG, 0),
    [MAHOGANY_LOG]: new InventoryItem(MAHOGANY_LOG, 0),
    [YEW_LOG]: new InventoryItem(YEW_LOG, 0),

    [SHRIMP_NORMAL]: new InventoryItem(SHRIMP_NORMAL, 0),
    [SHRIMP_PRIME]: new InventoryItem(SHRIMP_PRIME, 0),
    [SHRIMP_MULTI]: new InventoryItem(SHRIMP_MULTI, 0),
    [SHRIMP_PRAWN]: new InventoryItem(SHRIMP_PRAWN, 0),

    [TROUT_HERRING]: new InventoryItem(TROUT_HERRING, 0),
    [TROUT_PRIME]: new InventoryItem(TROUT_PRIME, 0),
    [TROUT_SALMON]: new InventoryItem(TROUT_SALMON, 0),
    [TROUT_TROUT]: new InventoryItem(TROUT_TROUT, 0),

    [COPPER_ORE]: new InventoryItem(COPPER_ORE, 0), 
    [TIN_ORE]: new InventoryItem(TIN_ORE, 0), 
    [IRON_ORE]: new InventoryItem(IRON_ORE, 0), 
    [COAL_ORE]: new InventoryItem(COAL_ORE, 0), 
    [MITHRIL_ORE]: new InventoryItem(MITHRIL_ORE, 0), 
    [ADAMANTITE_ORE]: new InventoryItem(ADAMANTITE_ORE, 0), 
    [LUMINITE_ORE]: new InventoryItem(LUMINITE_ORE, 0), 
    [RUNITE_ORE]: new InventoryItem(RUNITE_ORE, 0), 
    [ORICHALCITE_ORE]: new InventoryItem(ORICHALCITE_ORE, 0), 
    [DRAKOLITH_ORE]: new InventoryItem(DRAKOLITH_ORE, 0), 
    [NECRITE_ORE]: new InventoryItem(NECRITE_ORE, 0), 
    [PHASMATITE_ORE]: new InventoryItem(PHASMATITE_ORE, 0), 
    [BANITE_ORE]: new InventoryItem(BANITE_ORE, 0), 
    [LIGHT_ANIMICA]: new InventoryItem(LIGHT_ANIMICA, 0), 
    [DARK_ANIMICA]: new InventoryItem(DARK_ANIMICA, 0), 
}

export interface BankItem {
    name: string
    icon: string
    count: number
}
